modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''NeoForge PermissionAPI経由で未承認ユーザーのワールド操作を制限するIVRM専用サーバーMOD。'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version}]"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"
