license="${mod_license}"
issueTrackerURL="https://github.com/ivRooom/ivrm-mcmod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/ivRooom/ivrm-mcmod"
authors="ivRooom"
description='''
生活鯖と資源鯖の間で、インベントリ・装備・経験値を安全に受け渡すサーバー専用MODです。
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"
